print("Austin Kenneth Lee Brown")
print("Pabellon de Arteaga")
print("04/Marzo/2002")
print("Blanco")
print("Lobo albino")
print("¿Qué es la programación?")
print("Es el proceso de tomar un algoritmo y codificarlo de manera que se pueda ser ejecutado por un programa o como un programa")
print("¿Por qué es importante la programación?")
print("La programacion es importante ya que nos permite descubrir nuevas capcidades logisticas y de esta manera no permite solucionar problemas de manera mas eficiente y de manera mas correcto")
print("Explique con sus palabras que es herencia")
print("Herencia es el proceso o accion de obtener algo de un odjeto anterior obteniendo su misma funcion")
print("Explique con sus palabras que es poliformismo")
print("es la habilidad de hacer que un mensaje funcione en varios objetos, seindo un solo mensaje")
print("Explique con sus palabras que es abstracción")
print("Es cuando algo no tiene un concepto o forma definida pero cada quien le da ese concepto o forma en base a su percepcion")
print("Explique con sus palabras que es encapsulamiento")
print("Es cuando unes todas las propiedas como funciones, color, etc de algun objeto abstracto y lo pones en una sola seccion")
